package com.bank.BSTMS.pojo;

import java.io.Serializable;

public class Account implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.CardId
     *
     * @mbggenerated
     */
    private String cardid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.AccountBalance
     *
     * @mbggenerated
     */
    private String accountbalance;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.Identify
     *
     * @mbggenerated
     */
    private String identify;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.Password
     *
     * @mbggenerated
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.Type
     *
     * @mbggenerated
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.CreditLimit
     *
     * @mbggenerated
     */
    private String creditlimit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.effectiveDate
     *
     * @mbggenerated
     */
    private String effectivedate;
	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table account
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.CardId
     *
     * @return the value of account.CardId
     *
     * @mbggenerated
     */
    public String getCardid() {
        return cardid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.CardId
     *
     * @param cardid the value for account.CardId
     *
     * @mbggenerated
     */
    public void setCardid(String cardid) {
        this.cardid = cardid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.AccountBalance
     *
     * @return the value of account.AccountBalance
     *
     * @mbggenerated
     */
    public String getAccountbalance() {
        return accountbalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.AccountBalance
     *
     * @param accountbalance the value for account.AccountBalance
     *
     * @mbggenerated
     */
    public void setAccountbalance(String accountbalance) {
        this.accountbalance = accountbalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.Identify
     *
     * @return the value of account.Identify
     *
     * @mbggenerated
     */
    public String getIdentify() {
        return identify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.Identify
     *
     * @param identify the value for account.Identify
     *
     * @mbggenerated
     */
    public void setIdentify(String identify) {
        this.identify = identify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.Password
     *
     * @return the value of account.Password
     *
     * @mbggenerated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.Password
     *
     * @param password the value for account.Password
     *
     * @mbggenerated
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.Type
     *
     * @return the value of account.Type
     *
     * @mbggenerated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.Type
     *
     * @param type the value for account.Type
     *
     * @mbggenerated
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.CreditLimit
     *
     * @return the value of account.CreditLimit
     *
     * @mbggenerated
     */
    public String getCreditlimit() {
        return creditlimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.CreditLimit
     *
     * @param creditlimit the value for account.CreditLimit
     *
     * @mbggenerated
     */
    public void setCreditlimit(String creditlimit) {
        this.creditlimit = creditlimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.effectiveDate
     *
     * @return the value of account.effectiveDate
     *
     * @mbggenerated
     */
    public String getEffectivedate() {
        return effectivedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.effectiveDate
     *
     * @param effectivedate the value for account.effectiveDate
     *
     * @mbggenerated
     */
    public void setEffectivedate(String effectivedate) {
        this.effectivedate = effectivedate;
    }
}