package com.bank.BSTMS.pojo;

import java.io.Serializable;

public class Bill implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill.CardID
     *
     * @mbggenerated
     */
    private String cardid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill.AffairType
     *
     * @mbggenerated
     */
    private String affairtype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill.TradeTime
     *
     * @mbggenerated
     */
    private String tradetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill.TradeBalance
     *
     * @mbggenerated
     */
    private String tradebalance;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table bill
     *
     * @mbggenerated
     */
	private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill.CardID
     *
     * @return the value of bill.CardID
     *
     * @mbggenerated
     */
    public String getCardid() {
        return cardid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill.CardID
     *
     * @param cardid the value for bill.CardID
     *
     * @mbggenerated
     */
    public void setCardid(String cardid) {
        this.cardid = cardid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill.AffairType
     *
     * @return the value of bill.AffairType
     *
     * @mbggenerated
     */
    public String getAffairtype() {
        return affairtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill.AffairType
     *
     * @param affairtype the value for bill.AffairType
     *
     * @mbggenerated
     */
    public void setAffairtype(String affairtype) {
        this.affairtype = affairtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill.TradeTime
     *
     * @return the value of bill.TradeTime
     *
     * @mbggenerated
     */
    public String getTradetime() {
        return tradetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill.TradeTime
     *
     * @param tradetime the value for bill.TradeTime
     *
     * @mbggenerated
     */
    public void setTradetime(String tradetime) {
        this.tradetime = tradetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill.TradeBalance
     *
     * @return the value of bill.TradeBalance
     *
     * @mbggenerated
     */
    public String getTradebalance() {
        return tradebalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill.TradeBalance
     *
     * @param tradebalance the value for bill.TradeBalance
     *
     * @mbggenerated
     */
    public void setTradebalance(String tradebalance) {
        this.tradebalance = tradebalance;
    }
}