package com.bank.BSTMS.pojo;

import java.io.Serializable;

public class User implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.Identify
     *
     * @mbggenerated
     */
    private String identify;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.Username
     *
     * @mbggenerated
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.TelNum
     *
     * @mbggenerated
     */
    private String telnum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.Address
     *
     * @mbggenerated
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.Identify
     *
     * @return the value of user.Identify
     *
     * @mbggenerated
     */
    public String getIdentify() {
        return identify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.Identify
     *
     * @param identify the value for user.Identify
     *
     * @mbggenerated
     */
    public void setIdentify(String identify) {
        this.identify = identify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.Username
     *
     * @return the value of user.Username
     *
     * @mbggenerated
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.Username
     *
     * @param username the value for user.Username
     *
     * @mbggenerated
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.TelNum
     *
     * @return the value of user.TelNum
     *
     * @mbggenerated
     */
    public String getTelnum() {
        return telnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.TelNum
     *
     * @param telnum the value for user.TelNum
     *
     * @mbggenerated
     */
    public void setTelnum(String telnum) {
        this.telnum = telnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.Address
     *
     * @return the value of user.Address
     *
     * @mbggenerated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.Address
     *
     * @param address the value for user.Address
     *
     * @mbggenerated
     */
    public void setAddress(String address) {
        this.address = address;
    }
}