package com.bank.BSTMS.mapper;

import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Component;

import com.bank.BSTMS.pojo.AccountCurrency;
@Component
@Mapper
public interface AccountCurrencyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_currency
     *
     * @mbggenerated
     */
    int insert(AccountCurrency record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_currency
     *
     * @mbggenerated
     */
    int insertSelective(AccountCurrency record);
}