package com.bank.BSTMS.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Component;

import com.bank.BSTMS.pojo.Bill;
@Component
@Mapper
public interface BillMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bill
     *
     * @mbggenerated
     */
	boolean insert(Bill record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bill
     *
     * @mbggenerated
     */
    int insertSelective(Bill record);
    List<Bill> selectByCardKey(String cardid);
}